### ISSUE TITLE
Roadmap and Feedback

### ISSUE THREAD

**Issue by sming256** [sming256/OpenTAD#1]
We keep this issue open to collect feature requests and feedback from users, and thus keep improving this codebase. 

If you didn't find the features you need in the [Road Map](https://github.com/sming256/OpenTAD/blob/main/docs/en/roadmap.md), please leave a message here.

Thank you!

**Comment by rixejzvdl649** [comment]
cool

**Comment by akshitac8** [comment]
Hi @sming256 Thank you for sharing the toolkit. Its really amazing, I wanted to the ask, the paper AdaTAD also has the parallel adapter approach, AdaTAD' (75.4 in paper) but when implementing it using the codebase shared I am able to achieve somewhere around 74.5 mAP, can you please share if there are any parameters are different between AdaTAD and AdaTAD'?

**Comment by sming256** [comment]
Only a few hyperparameters are changed, such as the mlp ratio in the adapter is changed from 1/4 to 1/8, and the learning rate is searched between 1e-4 to 5e-5. I will update the parallel backbone and checkpoint later.

**Comment by akshitac8** [comment]
That would be really helpful @sming256 for reproducing the results 😃.

**Comment by akshitac8** [comment]
Hi @sming256 wanted to check if you could please upload the parallel backbone code as well that would be great.

**Comment by Caspeerrr** [comment]
Are you planning to also release tridetplus in this toolkit? (https://github.com/dingfengshi/tridetplus) 
thanks!

**Comment by sming256** [comment]
@Caspeerrr Thanks for your suggestion! Integrating TriDetPlus into OpenTAD seems straightforward. However, TriDetPlus only released the VideoMAEv2 feature, not the DINO2 feature. This is the only reason we haven't integrated it now.

**Comment by sming256** [comment]
Hi @akshitac8 , the side tuning model is released [here](https://github.com/sming256/OpenTAD/blob/main/opentad/models/backbones/vit_ladder.py), and we provide a training example [here](https://github.com/sming256/OpenTAD/blob/main/configs/adatad/thumos/e2e_thumos_videomaev2_g_768x2_224_side_2e-4.py) .
When implementing the side-tuning with the latest OpenTAD, we find a performance drop of around 1% on THUMOS. In our released checkpoint, we achieve 74.65% mAP using VideoMAEv2-g.

**Comment by Harry-KIT** [comment]
Hi @sming256, Thank you for an excellent work. I have a question about open source datasets not yet included in this repo.

You mentioned as follows:
Support multiple TAD datasets. We support 9 TAD datasets, including ActivityNet-1.3, THUMOS-14, HACS, Ego4D-MQ, EPIC-Kitchens-100, FineAction, Multi-THUMOS, Charades, and EPIC-Sounds Detection datasets.

What about other open source datasets (e.g, AVA2, UCF24)?

**Comment by sming256** [comment]
Hi @Harry-KIT, thanks for your question. OpenTAD is designed for temporal action detection task. I think AVA2 and UCF24 are datasets of spatial-temporal action detection task, which requires additional spatial bounding boxes.

**Comment by Harry-KIT** [comment]
I see. Thank you very much

**Comment by BruParis** [comment]
Hello @sming256,
Thank you for sharing this amazing tool.

I noticed the Roadmap mentions 'Feature extraction code.' Could you provide more details on this point?
Do you plan to export the outputs of the backbone (adapter/ladder), or perhaps the intermediate projection within the detectors ?

Looking forward to hearing more about it.

**Comment by sming256** [comment]
Thanks for your question @BruParis .

We plan to release the feature extraction code to extract untrimmed video features, such as I3D/SlowFast/VideoMAE/InternVideo2. People can also add their own backbone models to the code to extract new features. Thus, the AdaTAD with adapters is also supported as the backbone.

Due to some refactoring work, we plan to release it next month.

**Comment by BruParis** [comment]
Alright, great !
Cannot wait to check this out !

Thank you for your answer.

**Comment by yilonghe** [comment]
Hi @sming256, Thank you for an excellent work. When I was conducting local training, I encountered the following errors. However, I haven't been able to find any possible solutions. I'm wondering if you have ever come across this problem. Additionally, occasionally the training can run smoothly, but this error occurs quite frequently.  

2025-04-11 16:32:58 Train INFO: [Train]: Epoch 2 started
2025-04-11 16:36:06 Train INFO: [Train]: [002][00050/00199]  Loss=0.9038  cls_loss=0.5724  reg_loss=0.3315  lr_backbone=4.5e-05  lr_det=4.5e-05  mem=14051MB
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 256141) of binary: /home/xh/anaconda3/envs/test/bin/python
Traceback (most recent call last):
  File "/home/xh/anaconda3/envs/test/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/xh/anaconda3/envs/test/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xh/anaconda3/envs/test/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xh/anaconda3/envs/test/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xh/anaconda3/envs/test/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xh/anaconda3/envs/test/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
tools/train.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-04-11_16:37:30
  host      : xh-Z790-D-AX
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 256141)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 256141
========================================================

**Comment by sming256** [comment]
Unfortunately, I haven't met this issue before. I suspect it could be related to some multiprocessing setting in Pytorch. @yilonghe

**Comment by ChouSQi** [comment]
Hello,
First, thank you so much for your excellent work on this project and for sharing the TAD models and datasets with the community.
I am writing to request your help regarding the dataset download. I have been trying to download the ActivityNet dataset (VideoMAE-Large-16x4x1 version) from the provided Google Drive link.
Unfortunately, due to persistent network instability in my region, the download frequently interrupts. This often results in a corrupted file, and I have been unable to successfully download the complete, valid dataset after many attempts.
I was wondering if it would be possible for you to provide an alternative download link for this specific dataset? If convenient, a link hosted on Baidu Netdisk (百度网盘) would be extremely helpful, as it tends to be much more stable and reliable for users in my location.
Thank you very much for your consideration and for any help you can provide!
