### ISSUE TITLE
During the training of adatad on thumos14, a RuntimeError: DataLoader worker (pid(s) 236072) exited unexpectedly occurred during validation.

### ISSUE THREAD

**Issue by zippyzzzlz** [sming256/OpenTAD#39]
hi:
I tried to train an adatad on a single-card single-machine in thumos raw video, and when I executed the command `torchrun --nnodes=1 --nproc_per_node=1 --rdzv_backend=c10d --rdzv_endpoint=localhost:0 tools/train.py configs/adatad/thumos/e2e_thumos_videomae_s_768x1_160_adapter.py` in the terminal, an error occurred.

```
41%|████████████████▉                        | 163/396 [04:05<05:51,  1.51s/it]
Traceback (most recent call last):
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 254531) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zippyzzzlz/OpenTAD/tools/train.py", line 229, in <module>
    main()
  File "/home/zippyzzzlz/OpenTAD/tools/train.py", line 214, in main
    eval_one_epoch(
  File "/home/zippyzzzlz/OpenTAD/tools/../opentad/cores/test_engine.py", line 49, in eval_one_epoch
    for i, data_dict in enumerate(tqdm.tqdm(test_loader, disable=(rank != 0))):
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 254531) exited unexpectedly
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 254383) of binary: /home/zippyzzzlz/anaconda3/envs/opentad/bin/python3.10
Traceback (most recent call last):
  File "/home/zippyzzzlz/anaconda3/envs/opentad/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zippyzzzlz/anaconda3/envs/opentad/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-26_15:37:16
  host      : zippyzzzlz-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 254383)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

The problem might be that test_loader is unable to read the next batch of data. I've tried the following: 

1. re-cloning the code
2. re-extracting the data/thumos-14/raw_data data
3. trying various combinations of batch_size and num_workers (e.g., val=dict(batch_size=1, num_workers=0), val=dict(batch_size=2, num_workers=0), val=dict(batch_size=8, num_workers=8))

but none of these worked. Every time, the code gets stuck at this point (41%|████████████████▉                        | 163/396 [04:05<05:51,  1.51s/it]) and throws an error.

Have you encountered this problem before? 
thanks

**Comment by sming256** [comment]
Please check your RAM. 

Usually it is because of running out of RAM, since some videos are very long in THUMOS.

**Comment by zippyzzzlz** [comment]
Thank you for your correction! It was indeed a careless error.
